//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class root
{

    private string tickerTextField;

    private string enableAlarmViewerField;

    private string scrollingField;

    private string speedField;

    private string disableNotesField;

    private string fontsizeField;

    private rootLocations[] locationsField;

    private rootHideColumns[] hideColumnsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string tickerText
    {
        get
        {
            return this.tickerTextField;
        }
        set
        {
            this.tickerTextField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string enableAlarmViewer
    {
        get
        {
            return this.enableAlarmViewerField;
        }
        set
        {
            this.enableAlarmViewerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string scrolling
    {
        get
        {
            return this.scrollingField;
        }
        set
        {
            this.scrollingField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string speed
    {
        get
        {
            return this.speedField;
        }
        set
        {
            this.speedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string disableNotes
    {
        get
        {
            return this.disableNotesField;
        }
        set
        {
            this.disableNotesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fontsize
    {
        get
        {
            return this.fontsizeField;
        }
        set
        {
            this.fontsizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("locations", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rootLocations[] locations
    {
        get
        {
            return this.locationsField;
        }
        set
        {
            this.locationsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("hideColumns", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rootHideColumns[] hideColumns
    {
        get
        {
            return this.hideColumnsField;
        }
        set
        {
            this.hideColumnsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class rootLocations
{

    private string idField;

    private string descriptionField;

    private string priorityField;

    private string plocIdField;

    private rootLocationsDelay[] delayField;

    private rootLocationsDown[] downField;

    private rootLocationsUP[] upField;

    private rootLocationsUtil[] utilField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string priority
    {
        get
        {
            return this.priorityField;
        }
        set
        {
            this.priorityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string plocId
    {
        get
        {
            return this.plocIdField;
        }
        set
        {
            this.plocIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Delay", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rootLocationsDelay[] Delay
    {
        get
        {
            return this.delayField;
        }
        set
        {
            this.delayField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Down", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rootLocationsDown[] Down
    {
        get
        {
            return this.downField;
        }
        set
        {
            this.downField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Up", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rootLocationsUP[] Up
    {
        get
        {
            return this.upField;
        }
        set
        {
            this.upField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Util", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rootLocationsUtil[] Util
    {
        get
        {
            return this.utilField;
        }
        set
        {
            this.utilField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class rootLocationsDelay
{

    private string plocCField;

    private string alarmField;

    private string alarmIdField;

    private string alarmCountField;

    private string noteField;

    private string isAcknowledgeField;

    private string isMaintenanceField;

    private string durationField;

    private string ohDurationField;

    private string priortyColorField;

    private string noteColorField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string plocC
    {
        get
        {
            return this.plocCField;
        }
        set
        {
            this.plocCField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string alarm
    {
        get
        {
            return this.alarmField;
        }
        set
        {
            this.alarmField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string alarmId
    {
        get
        {
            return this.alarmIdField;
        }
        set
        {
            this.alarmIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string alarmCount
    {
        get
        {
            return this.alarmCountField;
        }
        set
        {
            this.alarmCountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string note
    {
        get
        {
            return this.noteField;
        }
        set
        {
            this.noteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string isAcknowledge
    {
        get
        {
            return this.isAcknowledgeField;
        }
        set
        {
            this.isAcknowledgeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string isMaintenance
    {
        get
        {
            return this.isMaintenanceField;
        }
        set
        {
            this.isMaintenanceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string duration
    {
        get
        {
            return this.durationField;
        }
        set
        {
            this.durationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ohDuration
    {
        get
        {
            return this.ohDurationField;
        }
        set
        {
            this.ohDurationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string priortyColor
    {
        get
        {
            return this.priortyColorField;
        }
        set
        {
            this.priortyColorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string noteColor
    {
        get
        {
            return this.noteColorField;
        }
        set
        {
            this.noteColorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class rootLocationsDown
{

    private string plocCField;

    private string alarmField;

    private string alarmIdField;

    private string alarmCountField;

    private string noteField;

    private string isAcknowledgeField;

    private string isMaintenanceField;

    private string durationField;

    private string ohDurationField;

    private string priortyColorField;

    private string noteColorField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string plocC
    {
        get
        {
            return this.plocCField;
        }
        set
        {
            this.plocCField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string alarm
    {
        get
        {
            return this.alarmField;
        }
        set
        {
            this.alarmField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string alarmId
    {
        get
        {
            return this.alarmIdField;
        }
        set
        {
            this.alarmIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string alarmCount
    {
        get
        {
            return this.alarmCountField;
        }
        set
        {
            this.alarmCountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string note
    {
        get
        {
            return this.noteField;
        }
        set
        {
            this.noteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string isAcknowledge
    {
        get
        {
            return this.isAcknowledgeField;
        }
        set
        {
            this.isAcknowledgeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string isMaintenance
    {
        get
        {
            return this.isMaintenanceField;
        }
        set
        {
            this.isMaintenanceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string duration
    {
        get
        {
            return this.durationField;
        }
        set
        {
            this.durationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ohDuration
    {
        get
        {
            return this.ohDurationField;
        }
        set
        {
            this.ohDurationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string priortyColor
    {
        get
        {
            return this.priortyColorField;
        }
        set
        {
            this.priortyColorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string noteColor
    {
        get
        {
            return this.noteColorField;
        }
        set
        {
            this.noteColorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class rootLocationsUP
{

    private string plocCField;

    private string alarmField;

    private string alarmIdField;

    private string alarmCountField;

    private string noteField;

    private string isAcknowledgeField;

    private string isMaintenanceField;

    private string durationField;

    private string ohDurationField;

    private string priortyColorField;

    private string noteColorField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string plocC
    {
        get
        {
            return this.plocCField;
        }
        set
        {
            this.plocCField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string alarm
    {
        get
        {
            return this.alarmField;
        }
        set
        {
            this.alarmField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string alarmId
    {
        get
        {
            return this.alarmIdField;
        }
        set
        {
            this.alarmIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string alarmCount
    {
        get
        {
            return this.alarmCountField;
        }
        set
        {
            this.alarmCountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string note
    {
        get
        {
            return this.noteField;
        }
        set
        {
            this.noteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string isAcknowledge
    {
        get
        {
            return this.isAcknowledgeField;
        }
        set
        {
            this.isAcknowledgeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string isMaintenance
    {
        get
        {
            return this.isMaintenanceField;
        }
        set
        {
            this.isMaintenanceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string duration
    {
        get
        {
            return this.durationField;
        }
        set
        {
            this.durationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ohDuration
    {
        get
        {
            return this.ohDurationField;
        }
        set
        {
            this.ohDurationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string priortyColor
    {
        get
        {
            return this.priortyColorField;
        }
        set
        {
            this.priortyColorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string noteColor
    {
        get
        {
            return this.noteColorField;
        }
        set
        {
            this.noteColorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class rootLocationsUtil
{

    private string plocCField;

    private string alarmField;

    private string alarmIdField;

    private string alarmCountField;

    private string noteField;

    private string isAcknowledgeField;

    private string isMaintenanceField;

    private string durationField;

    private string ohDurationField;

    private string priortyColorField;

    private string noteColorField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string plocC
    {
        get
        {
            return this.plocCField;
        }
        set
        {
            this.plocCField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string alarm
    {
        get
        {
            return this.alarmField;
        }
        set
        {
            this.alarmField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string alarmId
    {
        get
        {
            return this.alarmIdField;
        }
        set
        {
            this.alarmIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string alarmCount
    {
        get
        {
            return this.alarmCountField;
        }
        set
        {
            this.alarmCountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string note
    {
        get
        {
            return this.noteField;
        }
        set
        {
            this.noteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string isAcknowledge
    {
        get
        {
            return this.isAcknowledgeField;
        }
        set
        {
            this.isAcknowledgeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string isMaintenance
    {
        get
        {
            return this.isMaintenanceField;
        }
        set
        {
            this.isMaintenanceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string duration
    {
        get
        {
            return this.durationField;
        }
        set
        {
            this.durationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ohDuration
    {
        get
        {
            return this.ohDurationField;
        }
        set
        {
            this.ohDurationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string priortyColor
    {
        get
        {
            return this.priortyColorField;
        }
        set
        {
            this.priortyColorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string noteColor
    {
        get
        {
            return this.noteColorField;
        }
        set
        {
            this.noteColorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class rootHideColumns
{

    private string hideColumnField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string hideColumn
    {
        get
        {
            return this.hideColumnField;
        }
        set
        {
            this.hideColumnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class NewDataSet
{

    private root[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("root")]
    public root[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}
